'use client'
import './globals.css'
import React from 'react'
import { ChakraProvider, extendTheme } from "@chakra-ui/react"
import { modalTheme } from './components/theme/components/modal';



const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const theme = extendTheme({
  components: {
    Modal: modalTheme
  },
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="ja" className=''>
        <body className='w-screen h-screen'>
          <ChakraProvider resetCSS={false} theme={theme}>
            {children}
          </ChakraProvider>
        </body>
      </html>
  )
}
